library:
  script:
    - dub build
  stage: build
  only:
    - master
  tags:
    - D

test:
  script:
    - dub build --build=unittest --root=test --config=fullunittest
    - unbuffer test/libirl-test
  stage: test
  only:
    - master
  tags:
    - D
