library:
  script:
    - dub build
    - dub build --build=unittest --root=test
  stage: build
  only:
    - master
  tags:
    - D

test:
  script:
    - test/libirl-test
  stage: test
  only:
    - master
  tags:
    - D
